# Changes here will be overwritten by Copier
_commit: 1.5.2
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: mathysgrapotte@gmail.com
author_fullname: Mathys Grapotte
author_username: mathysgrapotte
copyright_date: '2024'
copyright_holder: Mathys Grapotte
copyright_holder_email: mathysgrapotte@gmail.com
copyright_license: MIT License
insiders: false
project_description: ''
project_name: stimulus-py
python_package_command_line_name: ''
python_package_distribution_name: stimulus-py
python_package_import_name: stimulus
repository_name: stimulus-py
repository_namespace: mathysgrapotte
repository_provider: github.com

